### ISSUE TITLE
google图像验证库不能正确的重定向

### ISSUE THREAD

**Issue by jhd147350** [justjavac/ReplaceGoogleCDN#101]
开发者你好！
这个网站的登录 有验证https://codepen.io/login，打开控制台发现google的图像验证库没有正确的重定向。
然而 https://www.google.com/recaptcha/api.js?onload=captchaOnload&render=explicit 我贴到浏览器地址栏是可以正确重定向的
https://www.recaptcha.net/recaptcha/api.js?onload=captchaOnload&render=explicit

不清楚具体是什么原因，我系统是win10，浏览器是edge 105.0.1343.27

**Comment by jingjingxyk** [comment]
> 开发者你好！ 这个网站的登录 有验证[https://codepen.io/login，打开控制台发现google的图像验证库没有正确的重定向。](https://codepen.io/login%EF%BC%8C%E6%89%93%E5%BC%80%E6%8E%A7%E5%88%B6%E5%8F%B0%E5%8F%91%E7%8E%B0google%E7%9A%84%E5%9B%BE%E5%83%8F%E9%AA%8C%E8%AF%81%E5%BA%93%E6%B2%A1%E6%9C%89%E6%AD%A3%E7%A1%AE%E7%9A%84%E9%87%8D%E5%AE%9A%E5%90%91%E3%80%82) 然而 https://www.google.com/recaptcha/api.js?onload=captchaOnload&render=explicit 我贴到浏览器地址栏是可以正确重定向的 https://www.recaptcha.net/recaptcha/api.js?onload=captchaOnload&render=explicit
> 
> 不清楚具体是什么原因，我系统是win10，浏览器是edge 105.0.1343.27

你的扩展是扩展市场下载的，还是本源码站下载的

**Comment by jhd147350** [comment]
@jingjingxyk 谢谢你的答复，我在edge扩展市场下载的。现在知道原因了，我再研究下源码，自己琢磨琢磨。那我先关闭issue了。非常感谢！

**Comment by jingjingxyk** [comment]
> 扩展市场里的代码版本，落后于本仓库代码的版本，扩展市场里的代码，需要作者更新。扩展市场里的代码，还是mainifest v2版本。本仓库已经更新到manifest v3 。

**Comment by jingjingxyk** [comment]
> @jingjingxyk 谢谢你的答复，我在edge扩展市场下载的。现在知道原因了，我再研究下源码，自己琢磨琢磨。那我先关闭issue了。非常感谢！

想自己解决，自己动手下载源码，即可，修改也很简单，修改一下json 文件即可。新版的都不用自己写javascript 代码了。只需要修改json文件

**Comment by jingjingxyk** [comment]
![Screenshot-2-gimp](https://user-images.githubusercontent.com/6836228/189843670-1cfef4ee-d82a-4e7b-9462-9f3860928296.png)

**Comment by jingjingxyk** [comment]
> @jingjingxyk 谢谢你的答复，我在edge扩展市场下载的。现在知道原因了，我再研究下源码，自己琢磨琢磨。那我先关闭issue了。非常感谢！

最新版已经可以可视化配置了

![可视化配置](https://raw.githubusercontent.com/jingjingxyk/ReplaceGoogleCDN/master/extension/screenshot/ReplaceGoogleCDN-2022-10-04%2016-01-38%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)
