### ISSUE TITLE
lolinet G 了啊

### ISSUE THREAD

**Issue by wolfcon** [justjavac/ReplaceGoogleCDN#110]
默认的 Lolinet G 了啊, 麻烦看看吧

**Comment by jingjingxyk** [comment]
当服务挂了，可用于替换的地址，已经写好了，直接能用： https://github.com/justjavac/ReplaceGoogleCDN/tree/master/extension/rules/mirrors


使用自定义规则： https://github.com/justjavac/ReplaceGoogleCDN/issues/115

**Comment by jingjingxyk** [comment]
自己切换就好了
![默认规则切换选项](https://user-images.githubusercontent.com/6836228/203980312-2db5aedd-05f8-4dcf-a168-98e107cdbaf1.png)

**Comment by wolfcon** [comment]
感谢~
