### ISSUE TITLE
自定义规则在哪

### ISSUE THREAD

**Issue by LiaoYifan2021** [justjavac/ReplaceGoogleCDN#115]
RT

**Comment by LiaoYifan2021** [comment]
因为loli寄了，所以要改

**Comment by jingjingxyk** [comment]
> 因为loli寄了，所以要改

全挂了吗？


扩展选项页，自己添加哈  


备注： 扩展市场里的版本落后于本仓库版本哈

**Comment by jingjingxyk** [comment]
参考： 

[google图像验证库不能正确的重定向](https://github.com/justjavac/ReplaceGoogleCDN/issues/101)
[增加 raw.githubusercontent.com =》raw.staticdn.net ](https://github.com/justjavac/ReplaceGoogleCDN/issues/98)

**Comment by jingjingxyk** [comment]
> 

选择详情
![image](https://user-images.githubusercontent.com/6836228/202854331-83b41ab0-d8d4-4687-b7a8-cad97e65cfd7.png)

选择扩展选项页
![image](https://user-images.githubusercontent.com/6836228/202854382-b6066c84-934a-441d-bd0c-94c241d1550c.png)


选项三：
![image](https://user-images.githubusercontent.com/6836228/202854442-22e36bb7-e61d-4c23-80d9-cb6e4ebe3f18.png)
