### ISSUE TITLE
你好，可以同步更新edge插件吗

### ISSUE THREAD

**Issue by iseeyo** [justjavac/ReplaceGoogleCDN#166]
chrome扩展中心已经是最新版了，edge扩展中心还是0.9.0旧版本

**Comment by justjavac** [comment]
我下午更新一下

**Comment by JY-H36** [comment]
> 我下午更新一下

大佬，最新版的zip文件解压后，chrome的扩展程序在哪啊，我是小白，找不到

**Comment by justjavac** [comment]
@JY-H36 extension 目录就是

**Comment by lzimd** [comment]
Edge 扩展(v0.10.25)，打包没有添加 josdejong/svelte-jsoneditor，导致扩展选项页加载失败，没法编辑。

**Comment by jingjingxyk** [comment]
啊。我更新以下

**Comment by jingjingxyk** [comment]
@justjavac  https://github.com/justjavac/ReplaceGoogleCDN/pull/167/files

**Comment by jingjingxyk** [comment]
@justjavac  删除 单条规则时，出现重复渲染 DOM 节点 的  bug  ，通过重新组织代码解决问题。 https://github.com/justjavac/ReplaceGoogleCDN/pulls

**Comment by justjavac** [comment]
via #168
