### ISSUE TITLE
默认规则导致 codelabs.developers.google.com 无法访问，该怎么修改啊

### ISSUE THREAD

**Issue by Vixb1122** [justjavac/ReplaceGoogleCDN#182]

**Comment by jingjingxyk** [comment]
@Vixb1122  我看了下，这是bug，规则 ID=17这条规则，匹配过于宽泛。规则所在行： https://github.com/justjavac/ReplaceGoogleCDN/blob/1171dfeca7a00c3b9aa5d9d80aed26b7fd15418b/extension/rules/rules_redirect_main.json#L308

## 解决办法：

方法一：
修改扩展源码：默认规则 https://github.com/justjavac/ReplaceGoogleCDN/blob/1171dfeca7a00c3b9aa5d9d80aed26b7fd15418b/extension/rules/rules_redirect_main.json


`"urlFilter": "developers.google.com"` 变更为 `"urlFilter": "https://developers.google.com"` 


![image](https://github.com/justjavac/ReplaceGoogleCDN/assets/6836228/83618ec2-a77a-4a48-8cdd-a5f3e20f307c)

方法二：优先级覆盖（我正在尝试），待反馈

**Comment by jingjingxyk** [comment]
解决思路： 添加scheme 匹配，收缩匹配范围 ：  https://github.com/justjavac/ReplaceGoogleCDN/pull/184
