### ISSUE TITLE
请问此扩展与 LocalCDN 扩展是否有冲突，建议二者一起使用吗？

### ISSUE THREAD

**Issue by C1og** [justjavac/ReplaceGoogleCDN#202]
LocalCDN: https://www.localcdn.org/

**Comment by jingjingxyk** [comment]
@C1og 扩展之间无冲突， 部分地址重定向功能 重叠。



你可以把    `LocalCDN   看作 https://github.com/justjavac/ReplaceGoogleCDN/blob/master/public-cdn.md
