### ISSUE TITLE
我这儿还是访问不了stackoverflow, 帮忙看看如何解决，谢谢。

### ISSUE THREAD

**Issue by valuex** [justjavac/ReplaceGoogleCDN#210]
edge 报错信息如下：
```
Requested host does not match any Subject Alternative Names (SANs) on TLS certificate [802825678933b3b920dfef799204b885942e45bef63cbbb04f6c2aceef8b305a] in use with this connection.

Visit https://docs.fastly.com/en/guides/common-400-errors#error-421-misdirected-request for more information.
```
帮忙看看如何解决，谢谢。

**Comment by jingjingxyk** [comment]
> edge 报错信息如下：
> 
> ```
> Requested host does not match any Subject Alternative Names (SANs) on TLS certificate [802825678933b3b920dfef799204b885942e45bef63cbbb04f6c2aceef8b305a] in use with this connection.
> 
> Visit https://docs.fastly.com/en/guides/common-400-errors#error-421-misdirected-request for more information.
> ```
> 
> 帮忙看看如何解决，谢谢。

打开浏览器控制台 ，截图控制台报错信息

**Comment by valuex** [comment]
报错信息：
![image](https://github.com/user-attachments/assets/c95e2cbe-21f1-44bf-8c8e-85a3b3587c3d)

**Comment by valuex** [comment]
问题已解决。检查了下电脑的hosts，发现是之前配置的IP不好用了。
