### ISSUE TITLE
FireFox扩展导致SEC_ERROR_REUSED_ISSUER_AND_SERIAL错误

### ISSUE THREAD

**Issue by Elite-stay** [justjavac/ReplaceGoogleCDN#25]
即使移除了扩展还是这样

E: 重装扩展之后再次移除似乎再也没有出现类似证书的情况，可能跟之前移除之前先禁用了扩展有关？

**Comment by KrasnayaPloshchad** [comment]
建议比较下这个分支，兴许能解决问题：
https://github.com/i36lib/ReplaceGoogleCDN
