### ISSUE TITLE
chrome//extensions 加载后任何无法访问http://localhost:9999/

### ISSUE THREAD

**Issue by YangFight** [justjavac/ReplaceGoogleCDN#37]
1.下载最新https://github.com/justjavac/ReplaceGoogleCDN.git仓库文件；
2.chrome浏览器输入：chrome//extensions后进入扩展程序界面；
3.打开开发者模式--》加载已解压的扩展程序--》选择将刚才下载库文件中“chrome”目录加载；
4.chrome扩展程序界面出现“Replace Google CDN 0.3.0”插件；
5.关闭chrome开发者模式；
6.chrome浏览器访问“http://localhost:9999/”提示依旧无法打开。
说明：下载的chrome文件包含“icons”和“js”两个文件夹以及“manifest.json”文件。

请各路大侠指导一下问题出在哪里？ 谢谢

**Comment by justjavac** [comment]
`http://localhost:9999` 是你的本地服务吗？

**Comment by YangFight** [comment]
http://localhost:9999 是battery-historian工具电量调试工具。
