### ISSUE TITLE
清单文件缺失或不可读取

### ISSUE THREAD

**Issue by qiang-zhang-neu** [justjavac/ReplaceGoogleCDN#45]
加载已解压的扩展程序的时候，报错了：

未能成功加载扩展程序
错误：清单文件确实或不可读取，无法加载清单。

这个错误要怎么解决？

**Comment by raindeavor** [comment]
你是不是直接打开最外层文件夹了，chrome的话，打开外层文件夹里面的chrome。

**Comment by llllllllllllllily** [comment]
> 你是不是直接打开最外层文件夹了，chrome的话，打开外层文件夹里面的chrome。

同遇到这个问题，建议作者标注一下要打开最外层文件夹里面的chrome,对小白比较友好

**Comment by justjavac** [comment]
忘了更新 readme 了，之前是没有 chrome 文件夹的，后来因为要主持 Firefox 和 edge，因此加了文件夹。我现在修改一下

**Comment by xuezhanpingrang** [comment]
最近需要用到yandex浏览器安装插件，也是解压的压缩包，也提示清单文件缺失或不可读取，安卓11的手机，穷尽了网上的教程，无结果，有网友说是安卓11的锅，不知道各位怎么看？

**Comment by xuezhanpingrang** [comment]
我的是vivo手机，找遍了，没有找到extension文件夹，能具体指导一下吗?不胜感激。

**Comment by justjavac** [comment]
> 我添加的proxy omega和ublock，是从网上下载的，不是从github下载的，就是用手机rar解压到手机，然后加载未打包的文件就可以了，以前都可以的，现在安卓11不行 了，提示清单缺失或不可读取。

https://github.com/justjavac/ReplaceGoogleCDN/archive/refs/heads/master.zip
