### ISSUE TITLE
基于Chromium的Edge出来了，能把这个扩展发布到Microsoft Store吗？

### ISSUE THREAD

**Issue by LiuJu150** [justjavac/ReplaceGoogleCDN#46]
基于Chromium的Edge出来了，能把这个扩展发布到Microsoft Store吗？
这样Edge也能用这个扩展了

**Comment by justjavac** [comment]
昨天试了下，没找到扩展发布的入口

**Comment by GavinDingCoolapk** [comment]
非常想要edge的扩展，用习惯了，哈哈

**Comment by SyndicateYe** [comment]
> 昨天试了下，没找到扩展发布的入口
您好，这是发布扩展的地址
https://developer.microsoft.com/zh-cn/microsoft-edge/extensions/

**Comment by justjavac** [comment]
@SyndicateYe 谢谢，已发布，正在审核

**Comment by justjavac** [comment]
https://microsoftedge.microsoft.com/addons/detail/replace-google-cdn/cojepngjobmaiajphkijbdcdjnnjhpjc
