### ISSUE TITLE
有两点请教下。

### ISSUE THREAD

**Issue by panxw** [justjavac/ReplaceGoogleCDN#5]
1，软件如何用？
2，https://chrome.google.com/webstore/detail/replace-google-cdn/kpampjmfiopfpkkepbllemkibefkiice
这个地址不翻墙，现在完全打不开，能否放到Github上。

**Comment by dishuostec** [comment]
1，这是个Chrome插件，安装后无需任何设置。
2，这个仓库就是插件的全部源代码，你可以克隆到本地，然后使用开发者模式加载本地的插件

**Comment by baixinyu** [comment]
做了一个翻墙的梯子，梯子好坏暂且不论，却把梯子放到了墙上。
