### ISSUE TITLE
USTC cdn 不可用

### ISSUE THREAD

**Issue by venzotsai** [justjavac/ReplaceGoogleCDN#53]
建议更换为极客族cdn：
Google前端库（Google Hosted Libraries）
源地址：//ajax.googleapis.com/
替换为：//gapis.geekzu.org/ajax/

谷歌字体库（Google Fonts）
源地址：//fonts.googleapis.com
替换为：//fonts.geekzu.org

字体文件（Google Fonts）
源地址：//fonts.gstatic.com/
替换为：//gapis.geekzu.org/g-fonts/

字体文件（Google Fonts）
源地址：//themes.googleusercontent.com/
替换为：//gapis.geekzu.org/g-themes/

**Comment by lihe1639** [comment]
小白不明白什么意思
