### ISSUE TITLE
stackoverflow Human Verification 的时候报错了

### ISSUE THREAD

**Issue by fengsmith** [justjavac/ReplaceGoogleCDN#56]
stackoverflow Human Verification 的时候报错了，这个 js 访问不了，有替换的网址没？
https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit&hl=en

**Comment by justjavac** [comment]
可以解决，`www.google.com` 替换为 `www.recaptcha.net` 就可以了，后者没有被墙。我下午改一下，重新发一个版本

**Comment by justjavac** [comment]
（PS：好像谷歌应用市场把我的扩展下架了😂）

**Comment by justjavac** [comment]
这个应该已经替换玩了，最新版

**Comment by fengsmith** [comment]
谢谢，我是在百度网盘下载的，后来才看到这个仓库的
