### ISSUE TITLE
请添加securetoken.googleapis.com的CDN替换

### ISSUE THREAD

**Issue by dixiatielu** [justjavac/ReplaceGoogleCDN#58]
GitBook本来可以访问，结果登录页面用了securetoken.googleapis.com，然后……就上不去了。希望作者增加这个API。

**Comment by justjavac** [comment]
这个可以试试修改 hosts，对应的 ip 地址为 https://site.ip138.com/securetoken.googleapis.com/ 你可以 ping 一下，找一个延迟最低的

**Comment by dixiatielu** [comment]
> 这个可以试试修改 hosts，对应的 ip 地址为 https://site.ip138.com/securetoken.googleapis.com/ 你可以 ping 一下，找一个延迟最低的

我刚刚ping了一下，全部都是请求超时...

**Comment by dixiatielu** [comment]
可以Reopen一下吗😅
我刚刚来试着ping了一下issue就被close了🤣🤣
@justjavac

**Comment by justjavac** [comment]
那这个就解决不了了。因为这个不是资源，而是有服务。只能通过代理解决了
