### ISSUE TITLE
www.google.com/cse 有替换资源吗？

### ISSUE THREAD

**Issue by ctrl2wei** [justjavac/ReplaceGoogleCDN#72]
我经常访问的博客引用了 https://www.google.com/cse/style/look/default.css ，打开时间巨慢。

**Comment by justjavac** [comment]
这个是什么啊

**Comment by ctrl2wei** [comment]
![image](https://user-images.githubusercontent.com/35016457/120914117-7e551580-c6ce-11eb-9803-bb9234ed2ec9.png)

![image](https://user-images.githubusercontent.com/35016457/120914138-9af14d80-c6ce-11eb-832b-f6727e59b67b.png)

**Comment by justjavac** [comment]
我搜了一下，cse 是 google 的账号服务，暂时没有对应的国内 cdn
