### ISSUE TITLE
安装上插件更慢了

### ISSUE THREAD

**Issue by gokuw** [justjavac/ReplaceGoogleCDN#73]
js脚本里面用的加速服务挂掉了吧，安装插件后反而更慢了
![image](https://user-images.githubusercontent.com/51148783/121284634-c616af80-c90f-11eb-9b8b-63a2be23f0a9.png)

**Comment by justjavac** [comment]
`blocked:other`，你使用了广告屏蔽的插件了吧

**Comment by gokuw** [comment]
啊，对，我开了adblock plus

**Comment by justjavac** [comment]
这个和插件无关，你再看看是哪个请求变慢了
