### ISSUE TITLE
Content Security Policy issues with some sites

### ISSUE THREAD

**Issue by AlexV525** [justjavac/ReplaceGoogleCDN#76]
https://pub.dev/packages/analyzer

ref: https://github.com/dart-lang/pub-dev/issues/5078

![image](https://user-images.githubusercontent.com/15884415/132185255-38340c45-591b-4037-beef-d1b8b4449c38.png)

![image](https://user-images.githubusercontent.com/15884415/132185556-d92fd9bc-2311-4a68-a460-3e731f7e1914.png)

**Comment by justjavac** [comment]
应该是被内容安全策略限制了

---------

![](https://user-images.githubusercontent.com/359395/132269878-b16c9aa9-f7cf-4b79-b053-604f75852754.png)

**Comment by justjavac** [comment]
本来加了相关代码，但是有 bug 就临时去除了，https://github.com/justjavac/ReplaceGoogleCDN/blob/master/extension/js/background.js#L31-L40

**Comment by AlexV525** [comment]
> 应该是被内容安全策略限制了

是的，尚未测试其它网站的复现情况。影响到图标展示后就无法看清主体内容了。

**Comment by jingjingxyk** [comment]
[已解决](https://github.com/justjavac/ReplaceGoogleCDN/pull/94/files)
