### ISSUE TITLE
StackOverflow 访问异常 

### ISSUE THREAD

**Issue by kyiree** [justjavac/ReplaceGoogleCDN#79]
访问 Stackoverflow 的时候带有 https://cdn.sstatic.net 前缀的静态资源均访问不了，开的是公司的 VPN，不知道是不是公司 VPN 墙了这部分资源还是其它原因
![issue2](https://user-images.githubusercontent.com/64623867/132933868-938a8360-9c7d-4a4c-880d-4447b3464820.jpg)

**Comment by kyiree** [comment]
能 ping 通上面网址的

**Comment by justjavac** [comment]
![image](https://user-images.githubusercontent.com/359395/136641121-25504dd4-ed9f-42de-8a08-50e358e40578.png)

**Comment by jingjingxyk** [comment]
@kyiree  解决了哈 https://github.com/justjavac/ReplaceGoogleCDN/issues/144
