### ISSUE TITLE
建议增加code.jquery.com 的替换

### ISSUE THREAD

**Issue by skipify** [justjavac/ReplaceGoogleCDN#88]
建议增加 code.jquery.com 的替换

**Comment by jingjingxyk** [comment]
> 建议增加 code.jquery.com 的替换


> [拨测  code.jquery.com 结果](https://zijian.aliyun.com/detect/dns/DNS_PING-2822c34baff9db99decd9d9de3a23986-1651428011235)

> 请发一个用到code.jquery.com, 打不开的例子出来。

> 好用于测试： https://github.com/jingjingxyk/ReplaceGoogleCDN/blob/v3-prune-jquery/extension/rules/rules-code-jquery-redirect.json
