### ISSUE TITLE
能不能弄一个safari版的

### ISSUE THREAD

**Issue by xclala** [justjavac/ReplaceGoogleCDN#92]
能不能弄一个safari版的

**Comment by justjavac** [comment]
我研究一下

**Comment by jingjingxyk** [comment]
挺简单的，按照这个来这个这个来，只需要把代码

https://developer.apple.com/documentation/safariservices/safari_web_extensions/creating_a_safari_web_extension

建议使用`manifest v2 `版本，直接把`https://github.com/justjavac/ReplaceGoogleCDN/tree/master/extension-v2`拷贝进去，按照提示稍微修改以下`manifest.json`就可以了

注意：因safari 对于`manifest v3 `支持不完整，比如rule里的action不支持modifyheader 方法，目前还不支持
